name: Labeler
on: pull_request

jobs:
  label:
    runs-on: ubuntu-latest
    steps:
      - name: PR-Labeller
        uses: actions/labeler@main
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          configuration-path: .github/labels.yml
